/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;

import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.curso.entity.Curso;
import javax.swing.JOptionPane;

import java.util.List;
/**
 *
 * @author misae
 */

//e aqui é a Classe que representa a tela para listar cursos

public class CursoListar extends javax.swing.JFrame {
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());

    /**
     * Creates new form CursoListar
     */
    
    private final CursoController controller = new CursoController(); 
    
    //aqui o objeto sorter para organizar as linhas da tabela conforme o filtro de pesquisa
    private TableRowSorter<DefaultTableModel> sorter;
    
    public CursoListar() {
        
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        jTable1.getColumnModel().getColumn(2).setMinWidth(0);
        jTable1.getColumnModel().getColumn(2).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(2).setWidth(0);

        // Carrega os cursos via Controller
        carregarCursos();
        
        // configura sorter para a tabela 
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);

        // document listener para filtrar enquanto digita
        txtProcurar.getDocument().addDocumentListener(new DocumentListener() {
        private void filtrar() {
        String texto = txtProcurar.getText();
        if (texto == null || texto.trim().isEmpty()) {
            sorter.setRowFilter(null);
            return;
        }
        
        // escapando caracteres especiais para evitar PatternSyntaxException
        String safe = Pattern.quote(texto);
        
        //aqui temos o Tratamentos de exceções na pratica
        try {
            // (?i) = case-insensitive, filtra na coluna 0 (nome)
            sorter.setRowFilter(RowFilter.regexFilter("(?i)^" + safe, 0));
        } catch (PatternSyntaxException ex) {
            // se algo der errado com a regex, remove o filtro
            sorter.setRowFilter(null);
        }
    }

        @Override
        public void insertUpdate(DocumentEvent e) { filtrar(); }
        @Override
        public void removeUpdate(DocumentEvent e) { filtrar(); }
        @Override
        public void changedUpdate(DocumentEvent e) { filtrar(); }
    });
    }
    
    public void carregarCursos() {
        
    try {
        List<Curso> cursos = controller.findAll();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Curso c : cursos) {
            model.addRow(new Object[]{c.getNome(), c.getCodigo(), c.getId()});
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Erro ao carregar cursos: " + e.getMessage());
    }
    
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtProcurar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtProcurar.setBackground(new java.awt.Color(255, 255, 255));
        txtProcurar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProcurar.setForeground(new java.awt.Color(80, 80, 80));
        txtProcurar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProcurar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));
        txtProcurar.setOpaque(true);
        txtProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcurarActionPerformed(evt);
            }
        });
        getContentPane().add(txtProcurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 250, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Codigo", "ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 510, 375));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 70, 50));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 30));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 30));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 30));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcurarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtProcurarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
    int linhaSelecionada = jTable1.getSelectedRow();

    if (linhaSelecionada == -1) {
    JOptionPane.showMessageDialog(this,
        "Selecione um curso para excluir!",
        "Aviso",
        JOptionPane.WARNING_MESSAGE);
    return;
    }

    // Agora usamos o ID oculto da tabela
    Long id = Long.valueOf(jTable1.getValueAt(linhaSelecionada, 2).toString());

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Excluir este curso?",
        "Confirmar",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {

    // buscar o curso pelo ID
    Curso curso = controller.findById(id);

    // excluir usando o método que já existe no controller
    controller.delete(curso);
    
    carregarCursos();

    JOptionPane.showMessageDialog(this, "Curso excluído!");
}


    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
     // cria uma nova janela JFrame para a tela de adicionar
     
    CursoAdicionar cursoAdicionar = new CursoAdicionar(this); // vai criar a tela de adicionar
    
    ///vai exibir a nova tabela
    cursoAdicionar.setVisible(true);
    cursoAdicionar.pack();  // pra ajustar o tamanho automatico
    
    cursoAdicionar.setLocationRelativeTo(null);  // aqui é pra centralizar a janela
    cursoAdicionar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);  

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      
    // Pega os dados da linha selecionada
    int linhaSelecionada = jTable1.getSelectedRow(); 

    // Verifica se uma linha foi selecionada
    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, 
            "Selecione um curso para editar!", 
            "Aviso", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Agora, pega o ID real da linha selecionada (coluna 2)
    Long idCurso = Long.valueOf(jTable1.getValueAt(linhaSelecionada, 2).toString()); // Acessando a coluna oculta para o ID

    // Busca o curso no banco pelo ID
    Curso curso = controller.findById(idCurso);
    
    

    // Verifica se o curso foi encontrado
    if (curso == null) {
        JOptionPane.showMessageDialog(this, 
            "Curso não encontrado no banco de dados!", 
            "Erro", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Abre a tela de edição com os dados verdadeiros do banco
    CursoEditar tela = new CursoEditar(
        this,
        curso.getId(),
        curso.getNome(),
        curso.getCodigo()
    );

    tela.setVisible(true);
    tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CursoListar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField txtProcurar;
    // End of variables declaration//GEN-END:variables
}
